manifest = "38f3715aa0feb716666cc0e728807b01f3d15060ecbcc841874d03c4e0d293b6"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
target = "//:detail"

[[dependency]]
package = "github.com/buckaroo-pm/boost-function"
target = "//:function"

[[dependency]]
package = "github.com/buckaroo-pm/boost-function_types"
target = "//:function_types"

[[dependency]]
package = "github.com/buckaroo-pm/boost-mpl"
target = "//:mpl"

[[dependency]]
package = "github.com/buckaroo-pm/boost-optional"
target = "//:optional"

[[dependency]]
package = "github.com/buckaroo-pm/boost-smart_ptr"
target = "//:smart_ptr"

[[dependency]]
package = "github.com/buckaroo-pm/boost-type_traits"
target = "//:type_traits"

[[dependency]]
package = "github.com/buckaroo-pm/boost-typeof"
target = "//:typeof"

[[dependency]]
package = "github.com/buckaroo-pm/boost-utility"
target = "//:utility"

[lock."github.com/buckaroo-pm/boost-bind"]
versions = [ "1.36.0" ]
revision = "20c264bf5bd431afcfc2f5bf44b4ad42522ee639"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.36.0" ]
revision = "137ef6f9d5cbf9e3b9b61ff052c564cb7bb3cd00"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.36.0" ]
revision = "743d10d29050a9543c2817effe9994af3e49e50f"

[lock."github.com/buckaroo-pm/boost-function"]
versions = [ "1.36.0" ]
revision = "2590206f90607b6cb75b27b448302efd321c6272"

[lock."github.com/buckaroo-pm/boost-function_types"]
versions = [ "1.36.0" ]
revision = "286afea518591daee9c82295007620493bbcf50e"

[lock."github.com/buckaroo-pm/boost-integer"]
versions = [ "1.36.0" ]
revision = "6cc827a89d06e4613782e92fc4cfd061eb5f2ee1"

[lock."github.com/buckaroo-pm/boost-mpl"]
versions = [ "1.36.0" ]
revision = "4ff0e16e88ea7ebda66803ecb2204549f4723092"

[lock."github.com/buckaroo-pm/boost-optional"]
versions = [ "1.36.0" ]
revision = "050de336c094ba90914800dec927f63a4d447448"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.36.0" ]
revision = "b4148f6e18ab2ceb5987f8bd3fd7984a8c94d5d7"

[lock."github.com/buckaroo-pm/boost-smart_ptr"]
versions = [ "1.36.0" ]
revision = "907c5ec3e3ea17d73ac83cda1093b976d6cdf98d"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.36.0" ]
revision = "86403ba725a22ed804f9a334784353b06d5ab963"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.36.0" ]
revision = "a6e835a3e205db8237e1d12501eb8f137e83e6dc"

[lock."github.com/buckaroo-pm/boost-typeof"]
versions = [ "1.36.0" ]
revision = "4994d329d58433491133d94fa1a5c5c4562ba8c7"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.36.0" ]
revision = "faafe390d89e84cfde454b587890539de6abb80a"
