targets = ["//:functional"]

[[dependency]]
package = "github.com/buckaroo-pm/boost-smart_ptr"
version = "1.50.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-optional"
version = "1.50.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
version = "1.50.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-type_traits"
version = "1.50.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
version = "1.50.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-typeof"
version = "1.50.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-utility"
version = "1.50.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-function_types"
version = "1.50.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-function"
version = "1.50.0"

[[dependency]]
package = "github.com/buckaroo-pm/boost-mpl"
version = "1.50.0"