manifest = "909f83fdcdec0c65083afb10960203292f241b1d2b6c82a5649493a1d3036a26"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-core"
target = "//:core"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
target = "//:detail"

[[dependency]]
package = "github.com/buckaroo-pm/boost-function"
target = "//:function"

[[dependency]]
package = "github.com/buckaroo-pm/boost-function_types"
target = "//:function_types"

[[dependency]]
package = "github.com/buckaroo-pm/boost-mpl"
target = "//:mpl"

[[dependency]]
package = "github.com/buckaroo-pm/boost-optional"
target = "//:optional"

[[dependency]]
package = "github.com/buckaroo-pm/boost-smart_ptr"
target = "//:smart_ptr"

[[dependency]]
package = "github.com/buckaroo-pm/boost-type_traits"
target = "//:type_traits"

[[dependency]]
package = "github.com/buckaroo-pm/boost-typeof"
target = "//:typeof"

[[dependency]]
package = "github.com/buckaroo-pm/boost-utility"
target = "//:utility"

[lock."github.com/buckaroo-pm/boost-align"]
versions = [ "1.57.0" ]
revision = "34efce4b58410d74186160b34f3cf5662ceab44f"

[lock."github.com/buckaroo-pm/boost-assert"]
versions = [ "1.57.0" ]
revision = "e4476f3159e98aebaa3a057bd2670653cb778d48"

[lock."github.com/buckaroo-pm/boost-bind"]
versions = [ "1.57.0" ]
revision = "b66482d2fa28ee1b1e30cc313601f4dd174a83a7"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.57.0" ]
revision = "ee7d5652f970bde066501c7cee1d0d2ad43c2348"

[lock."github.com/buckaroo-pm/boost-container_hash"]
versions = [ "1.57.0" ]
revision = "bcdddbb94c34c498170c0682716452220446733f"

[lock."github.com/buckaroo-pm/boost-core"]
versions = [ "1.57.0" ]
revision = "9194d8422e508b914041aad8c97a55b712cf4855"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.57.0" ]
revision = "08aef274380d048f40aea0f40be03d3c943c0917"

[lock."github.com/buckaroo-pm/boost-exception"]
versions = [ "1.57.0" ]
revision = "2d919cee0368f6dcef90b5010755588defadeb5e"

[lock."github.com/buckaroo-pm/boost-function"]
versions = [ "1.57.0" ]
revision = "4a227cf7787d8f3dbdeefcbb104dfca96decca08"

[lock."github.com/buckaroo-pm/boost-function_types"]
versions = [ "1.57.0" ]
revision = "7fa0e4ed64d4cbe8db4f11f0311e8f503662f96b"

[lock."github.com/buckaroo-pm/boost-integer"]
versions = [ "1.57.0" ]
revision = "305f54eaef314da61192948da2c632f65a64f02d"

[lock."github.com/buckaroo-pm/boost-move"]
versions = [ "1.57.0" ]
revision = "679b73ba4f8f2d6ea79655b6335089744e3259c3"

[lock."github.com/buckaroo-pm/boost-mpl"]
versions = [ "1.57.0" ]
revision = "11c429d65c6cea226770f7abf7b4af91419af893"

[lock."github.com/buckaroo-pm/boost-optional"]
versions = [ "1.57.0" ]
revision = "094fd219bbd887fa4db125cddf87ab7abe4537a8"

[lock."github.com/buckaroo-pm/boost-predef"]
versions = [ "1.57.0" ]
revision = "4e534e22df1a38d8046d3a84c091c3d0ddf35456"

[lock."github.com/buckaroo-pm/boost-preprocessor"]
versions = [ "1.57.0" ]
revision = "701273f2c2f1da1f06a00b11ee15f30a358a775c"

[lock."github.com/buckaroo-pm/boost-smart_ptr"]
versions = [ "1.57.0" ]
revision = "5c4652924dce06a9caac5ecd48eab45e19b70fc6"

[lock."github.com/buckaroo-pm/boost-static_assert"]
versions = [ "1.57.0" ]
revision = "1c6733c3798004871da07f1ca08b533b1293b597"

[lock."github.com/buckaroo-pm/boost-throw_exception"]
versions = [ "1.57.0" ]
revision = "7e886911750f84477833ba575aa654092c553cd4"

[lock."github.com/buckaroo-pm/boost-type_index"]
versions = [ "1.57.0" ]
revision = "bd3fed7df02979f8d00f4e78c022e866bc29a524"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.57.0" ]
revision = "b71c8285ba07563884f165ae769db3cd5a5dc45a"

[lock."github.com/buckaroo-pm/boost-typeof"]
versions = [ "1.57.0" ]
revision = "9a83b25172a84326263a7236784ed16a6df2ea6d"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.57.0" ]
revision = "672b552c874c72529564a79448c4b48b966ba7c5"
