targets = ["//:functional"]

[[dependency]]
package = "github.com/buckaroo-pm/boost-smart_ptr"
version = "1.16.1"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
version = "1.16.1"

[[dependency]]
package = "github.com/buckaroo-pm/boost-type_traits"
version = "1.16.1"

[[dependency]]
package = "github.com/buckaroo-pm/boost-utility"
version = "1.16.1"