manifest = "5f45d2f95eac1cf84245675e223a17297190b03d87f0bb30ac3706893a422d87"

[[dependency]]
package = "github.com/buckaroo-pm/boost-config"
target = "//:config"

[[dependency]]
package = "github.com/buckaroo-pm/boost-detail"
target = "//:detail"

[[dependency]]
package = "github.com/buckaroo-pm/boost-smart_ptr"
target = "//:smart_ptr"

[[dependency]]
package = "github.com/buckaroo-pm/boost-type_traits"
target = "//:type_traits"

[[dependency]]
package = "github.com/buckaroo-pm/boost-utility"
target = "//:utility"

[lock."github.com/buckaroo-pm/boost-config"]
versions = [ "1.18.3" ]
revision = "1b1749271198bc9eaae81e349875abc0881f6b05"

[lock."github.com/buckaroo-pm/boost-detail"]
versions = [ "1.18.3" ]
revision = "4dde65a65a3e50b4868420f4f7cd2c92db1e2942"

[lock."github.com/buckaroo-pm/boost-smart_ptr"]
versions = [ "1.18.3" ]
revision = "6a31332888f86f213862cfbcc0c66b02ef6ff26c"

[lock."github.com/buckaroo-pm/boost-type_traits"]
versions = [ "1.18.3" ]
revision = "c1f4845633560fcbbad71ffc4e56ea3eed603053"

[lock."github.com/buckaroo-pm/boost-utility"]
versions = [ "1.18.3" ]
revision = "283d65d2abf92a987441d9b74d26495cb0e98195"
